on:
  - push
  - pull_request
name: CI
jobs:
  spectralChecks:
    name: Spectral checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Spectral checks
        uses: ./
        with:
          file_glob: ./**/*.yml
          spectral_ruleset: .my-custom.spectral.yml
